# -*- coding: utf-8 -*-
"""Billing System-Drive through.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qN_fqPNThfDJMgEr1ohzcmHNtkm2v90t
"""

1#@title
print("                     Bill                         ");
print("           input item as exit to end.....");
it=[ ];
final=[ ];
total=0
while 1==1:
  item=input("your item is- ");
  it.append(item);
  if item=="exit":
    break
  print("your item is",item);
  unit=int(input("items unit price is-"));
  print("items unit price is",unit);
  quantity=int(input("quantity of item is-"));
  total=total+(unit*quantity);
  final.append(unit*quantity);
print("your items are",it);
print("please ignore 'exit'");
print("your grand total is",final)
print('you need to pay $',total);
print("thank you")
print("bye-bye :D   ..................");
print(".............................................................................");